### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by Caishen-git** [bit-isp/HSIR#6]
(cyq) ubuntu18@ubuntu18:~/cyq/Model-Guided-Deep-Hyperspectral-Image-Super-resolution-main/HSIR-main$ python  hsirun/test.py -a qrnn3d.qrnn3d -r qrnn3d.pth -t icvl_512_50
It seems that you have evaluated qrnn3d.qrnn3d before.

Are you sure you want to continue? (y) continue (n) exit
y
Traceback (most recent call last):
  File "hsirun/test.py", line 162, in <module>
    main(args, logdir)
  File "hsirun/test.py", line 112, in main
    net = tl.utils.instantiate(args.arch)
  File "/home/ubuntu18/.conda/envs/cyq/lib/python3.8/site-packages/torchlight/utils/helper.py", line 53, in instantiate
    return obj(*args, **kwargs)
TypeError: 'NoneType' object is not callable
(cyq) ubuntu18@ubuntu18:~/cyq/Model-Guided-Deep-Hyperspectral-Image-Super-resolution-main/HSIR-main$ 

Hello, I encountered this issue while using this tool. I hope you can give me some advice。
您好，我在使用这个工具的时候遇到了这个问题，我希望您能给我一下建议。
my wechat:15273115280

**Comment by Zeqiang-Lai** [comment]
please try full model path as 
```
python hsirun.test -a hsir.model.qrnn3d.qrnn3d -r qrnn3d.pth -t icvl_512_50
```
